# Generated by Django 4.1.4 on 2022-12-31 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0003_vote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='link',
        ),
    ]
