# Generated by Django 4.1.4 on 2022-12-31 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0004_remove_vote_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='link',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='links.link'),
            preserve_default=False,
        ),
    ]
